### ISSUE TITLE
feature: Add crate to crates.io

### ISSUE THREAD

**Issue by shovel-kun** [tree-sitter-grammars/tree-sitter-xcompose#1]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

Hi, I see that you have a rust bindings for this tree-sitter grammar, Will you be adding it to crates.io? I don't see it on your [crates.io profile](https://crates.io/users/ObserverOfTime). Thanks!

### Describe the solution you'd like

Add crate to crates.io

**Comment by ObserverOfTime** [comment]
Done.
